// Single source of truth for the equity universe every scanner tracks
// (fetch-stock-data, fundamentals-scanner, earnings-scanner, insider-scanner).
// Previously each function kept its own copy of this list, and they drifted:
// insider-scanner still had the original ~74-symbol list months after the
// other three grew to 115, silently missing insider-activity coverage on
// every ticker added since (including KMB, ABBV, and the rest of the
// dividend/small-cap additions). Import from here instead of hand-copying.
export interface TrackedSymbol { symbol: string; name: string }

export const TRACKED_SYMBOLS: TrackedSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc" },
  { symbol: "NVDA", name: "NVIDIA Corp" },
  { symbol: "TSLA", name: "Tesla Inc" },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "MSFT", name: "Microsoft Corp" },
  { symbol: "GOOGL", name: "Alphabet Inc" },
  { symbol: "AMZN", name: "Amazon.com Inc" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "NFLX", name: "Netflix Inc" },
  { symbol: "DIS", name: "Walt Disney Co" },
  { symbol: "JPM", name: "JPMorgan Chase & Co" },
  { symbol: "BAC", name: "Bank of America Corp" },
  { symbol: "XOM", name: "Exxon Mobil Corp" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "KO", name: "Coca-Cola Co" },
  { symbol: "WMT", name: "Walmart Inc" },
  { symbol: "V", name: "Visa Inc" },
  { symbol: "CRM", name: "Salesforce Inc" },
  { symbol: "ORCL", name: "Oracle Corp" },
  { symbol: "INTC", name: "Intel Corp" },
  { symbol: "ADBE", name: "Adobe Inc" },
  { symbol: "UBER", name: "Uber Technologies" },
  { symbol: "SOFI", name: "SoFi Technologies" },
  { symbol: "NIO", name: "NIO Inc" },
  { symbol: "PLUG", name: "Plug Power Inc" },
  { symbol: "SIRI", name: "Sirius XM Holdings" },
  { symbol: "NOK", name: "Nokia Corp" },
  { symbol: "F", name: "Ford Motor Co" },
  { symbol: "GPRO", name: "GoPro Inc" },
  { symbol: "CLOV", name: "Clover Health Investments" },
  { symbol: "BBAI", name: "BigBear.ai Holdings" },
  { symbol: "MARA", name: "MARA Holdings" },
  { symbol: "RIOT", name: "Riot Platforms" },
  { symbol: "SNDL", name: "SNDL Inc" },
  { symbol: "LCID", name: "Lucid Group" },
  { symbol: "CHPT", name: "ChargePoint Holdings" },
  { symbol: "FCEL", name: "FuelCell Energy" },
  { symbol: "IQ", name: "iQIYI Inc" },
  { symbol: "SNOW", name: "Snowflake Inc" },
  { symbol: "DDOG", name: "Datadog Inc" },
  { symbol: "NET", name: "Cloudflare Inc" },
  { symbol: "SHOP", name: "Shopify Inc" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "ROKU", name: "Roku Inc" },
  { symbol: "SNAP", name: "Snap Inc" },
  { symbol: "ABNB", name: "Airbnb Inc" },
  { symbol: "DASH", name: "DoorDash Inc" },
  { symbol: "TGT", name: "Target Corp" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "NKE", name: "Nike Inc" },
  { symbol: "SBUX", name: "Starbucks Corp" },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SCHW", name: "Charles Schwab Corp" },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "MRNA", name: "Moderna Inc" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "CVS", name: "CVS Health Corp" },
  { symbol: "BA", name: "Boeing Co" },
  { symbol: "GE", name: "General Electric Co" },
  { symbol: "FDX", name: "FedEx Corp" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "AAL", name: "American Airlines Group" },
  { symbol: "LUV", name: "Southwest Airlines Co" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc" },
  { symbol: "RIVN", name: "Rivian Automotive" },
  { symbol: "GM", name: "General Motors Co" },
  { symbol: "T", name: "AT&T Inc" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "CMCSA", name: "Comcast Corp" },
  // Small-cap ($300M-$2B-ish) -- everything above is large/mega-cap, so a
  // market-cap-based small-cap screen had nothing real to actually screen
  // without adding genuine small-cap names across a spread of sectors.
  { symbol: "CENX", name: "Century Aluminum Co" },
  { symbol: "ARRY", name: "Array Technologies" },
  { symbol: "SHLS", name: "Shoals Technologies Group" },
  { symbol: "PUBM", name: "PubMatic Inc" },
  { symbol: "MGNI", name: "Magnite Inc" },
  { symbol: "PERI", name: "Perion Network Ltd" },
  { symbol: "APPS", name: "Digital Turbine Inc" },
  { symbol: "AMRX", name: "Amneal Pharmaceuticals" },
  { symbol: "EVH", name: "Evolent Health Inc" },
  { symbol: "PGNY", name: "Progyny Inc" },
  { symbol: "CORT", name: "Corcept Therapeutics" },
  { symbol: "SUPN", name: "Supernus Pharmaceuticals" },
  { symbol: "BBW", name: "Build-A-Bear Workshop" },
  { symbol: "DLTH", name: "Duluth Trading Co" },
  { symbol: "DBI", name: "Designer Brands Inc" },
  { symbol: "CURV", name: "Torrid Holdings Inc" },
  { symbol: "TALO", name: "Talos Energy Inc" },
  { symbol: "CRK", name: "Comstock Resources Inc" },
  { symbol: "AMBA", name: "Ambarella Inc" },
  { symbol: "MXL", name: "MaxLinear Inc" },
  { symbol: "CEVA", name: "CEVA Inc" },
  { symbol: "PSTL", name: "Postal Realty Trust" },
  { symbol: "WSR", name: "Whitestone REIT" },
  { symbol: "GNE", name: "Genie Energy Ltd" },
  { symbol: "RAMP", name: "LiveRamp Holdings" },
  // Steady dividend payers -- deliberately boring, cash-generative
  // businesses (consumer staples, healthcare, utilities, industrials) as a
  // counterweight to the site's growth/momentum-heavy screens elsewhere.
  { symbol: "KMB", name: "Kimberly-Clark Corp" },
  { symbol: "ABBV", name: "AbbVie Inc" },
  { symbol: "PG", name: "Procter & Gamble Co" },
  { symbol: "PEP", name: "PepsiCo Inc" },
  { symbol: "MMM", name: "3M Co" },
  { symbol: "MO", name: "Altria Group Inc" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "O", name: "Realty Income Corp" },
  { symbol: "CVX", name: "Chevron Corp" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "MCD", name: "McDonald's Corp" },
  { symbol: "LMT", name: "Lockheed Martin Corp" },
  { symbol: "DUK", name: "Duke Energy Corp" },
  { symbol: "SO", name: "Southern Co" },
  { symbol: "MDT", name: "Medtronic plc" },
];

export const TRACKED_TICKERS: string[] = TRACKED_SYMBOLS.map((s) => s.symbol);
