// Single source of truth for the equity universe every scanner tracks
// (fetch-stock-data, fundamentals-scanner, earnings-scanner, insider-scanner).
// Previously each function kept its own copy of this list, and they drifted:
// insider-scanner still had the original ~74-symbol list months after the
// other three grew to 115, silently missing insider-activity coverage on
// every ticker added since (including KMB, ABBV, and the rest of the
// dividend/small-cap additions). Import from here instead of hand-copying.
export interface TrackedSymbol { symbol: string; name: string }

export const TRACKED_SYMBOLS: TrackedSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc" },
  { symbol: "NVDA", name: "NVIDIA Corp" },
  { symbol: "TSLA", name: "Tesla Inc" },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "MSFT", name: "Microsoft Corp" },
  { symbol: "GOOGL", name: "Alphabet Inc" },
  { symbol: "AMZN", name: "Amazon.com Inc" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "NFLX", name: "Netflix Inc" },
  { symbol: "DIS", name: "Walt Disney Co" },
  { symbol: "JPM", name: "JPMorgan Chase & Co" },
  { symbol: "BAC", name: "Bank of America Corp" },
  { symbol: "XOM", name: "Exxon Mobil Corp" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "KO", name: "Coca-Cola Co" },
  { symbol: "WMT", name: "Walmart Inc" },
  { symbol: "V", name: "Visa Inc" },
  { symbol: "CRM", name: "Salesforce Inc" },
  { symbol: "ORCL", name: "Oracle Corp" },
  { symbol: "INTC", name: "Intel Corp" },
  { symbol: "ADBE", name: "Adobe Inc" },
  { symbol: "UBER", name: "Uber Technologies" },
  { symbol: "SOFI", name: "SoFi Technologies" },
  { symbol: "NIO", name: "NIO Inc" },
  { symbol: "PLUG", name: "Plug Power Inc" },
  { symbol: "SIRI", name: "Sirius XM Holdings" },
  { symbol: "NOK", name: "Nokia Corp" },
  { symbol: "F", name: "Ford Motor Co" },
  { symbol: "GPRO", name: "GoPro Inc" },
  { symbol: "CLOV", name: "Clover Health Investments" },
  { symbol: "BBAI", name: "BigBear.ai Holdings" },
  { symbol: "MARA", name: "MARA Holdings" },
  { symbol: "RIOT", name: "Riot Platforms" },
  { symbol: "SNDL", name: "SNDL Inc" },
  { symbol: "LCID", name: "Lucid Group" },
  { symbol: "CHPT", name: "ChargePoint Holdings" },
  { symbol: "FCEL", name: "FuelCell Energy" },
  { symbol: "IQ", name: "iQIYI Inc" },
  { symbol: "SNOW", name: "Snowflake Inc" },
  { symbol: "DDOG", name: "Datadog Inc" },
  { symbol: "NET", name: "Cloudflare Inc" },
  { symbol: "SHOP", name: "Shopify Inc" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "ROKU", name: "Roku Inc" },
  { symbol: "SNAP", name: "Snap Inc" },
  { symbol: "ABNB", name: "Airbnb Inc" },
  { symbol: "DASH", name: "DoorDash Inc" },
  { symbol: "TGT", name: "Target Corp" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "NKE", name: "Nike Inc" },
  { symbol: "SBUX", name: "Starbucks Corp" },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SCHW", name: "Charles Schwab Corp" },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "MRNA", name: "Moderna Inc" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "CVS", name: "CVS Health Corp" },
  { symbol: "BA", name: "Boeing Co" },
  { symbol: "GE", name: "General Electric Co" },
  { symbol: "FDX", name: "FedEx Corp" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "AAL", name: "American Airlines Group" },
  { symbol: "LUV", name: "Southwest Airlines Co" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc" },
  { symbol: "RIVN", name: "Rivian Automotive" },
  { symbol: "GM", name: "General Motors Co" },
  { symbol: "T", name: "AT&T Inc" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "CMCSA", name: "Comcast Corp" },
  // Small-cap ($300M-$2B-ish) -- everything above is large/mega-cap, so a
  // market-cap-based small-cap screen had nothing real to actually screen
  // without adding genuine small-cap names across a spread of sectors.
  { symbol: "CENX", name: "Century Aluminum Co" },
  { symbol: "ARRY", name: "Array Technologies" },
  { symbol: "SHLS", name: "Shoals Technologies Group" },
  { symbol: "PUBM", name: "PubMatic Inc" },
  { symbol: "MGNI", name: "Magnite Inc" },
  { symbol: "PERI", name: "Perion Network Ltd" },
  { symbol: "APPS", name: "Digital Turbine Inc" },
  { symbol: "AMRX", name: "Amneal Pharmaceuticals" },
  { symbol: "EVH", name: "Evolent Health Inc" },
  { symbol: "PGNY", name: "Progyny Inc" },
  { symbol: "CORT", name: "Corcept Therapeutics" },
  { symbol: "SUPN", name: "Supernus Pharmaceuticals" },
  { symbol: "BBW", name: "Build-A-Bear Workshop" },
  { symbol: "DLTH", name: "Duluth Trading Co" },
  { symbol: "DBI", name: "Designer Brands Inc" },
  { symbol: "CURV", name: "Torrid Holdings Inc" },
  { symbol: "TALO", name: "Talos Energy Inc" },
  { symbol: "CRK", name: "Comstock Resources Inc" },
  { symbol: "AMBA", name: "Ambarella Inc" },
  { symbol: "MXL", name: "MaxLinear Inc" },
  { symbol: "CEVA", name: "CEVA Inc" },
  { symbol: "PSTL", name: "Postal Realty Trust" },
  { symbol: "WSR", name: "Whitestone REIT" },
  { symbol: "GNE", name: "Genie Energy Ltd" },
  { symbol: "RAMP", name: "LiveRamp Holdings" },
  // Steady dividend payers -- deliberately boring, cash-generative
  // businesses (consumer staples, healthcare, utilities, industrials) as a
  // counterweight to the site's growth/momentum-heavy screens elsewhere.
  { symbol: "KMB", name: "Kimberly-Clark Corp" },
  { symbol: "ABBV", name: "AbbVie Inc" },
  { symbol: "PG", name: "Procter & Gamble Co" },
  { symbol: "PEP", name: "PepsiCo Inc" },
  { symbol: "MMM", name: "3M Co" },
  { symbol: "MO", name: "Altria Group Inc" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "O", name: "Realty Income Corp" },
  { symbol: "CVX", name: "Chevron Corp" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "MCD", name: "McDonald's Corp" },
  { symbol: "LMT", name: "Lockheed Martin Corp" },
  { symbol: "DUK", name: "Duke Energy Corp" },
  { symbol: "SO", name: "Southern Co" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MP", name: "MP Materials Corp" },
  // Broad expansion (Aug 2026) -- the list above was a solid but narrow
  // cross-section. fetch-stock-data now processes the universe in
  // stalest-first partial batches instead of "everyone, every 5 minutes",
  // which is what makes a list this size safe to track without blowing
  // past Supabase's edge function execution ceiling -- see the BATCH_LIMIT
  // comment in fetch-stock-data/index.ts. Grouped by sector purely for
  // human readability; every scanner just imports the flat array.
  // Technology / software / semiconductors
  { symbol: "AVGO", name: "Broadcom Inc" },
  { symbol: "TXN", name: "Texas Instruments Inc" },
  { symbol: "ADI", name: "Analog Devices Inc" },
  { symbol: "LRCX", name: "Lam Research Corp" },
  { symbol: "KLAC", name: "KLA Corp" },
  { symbol: "AMAT", name: "Applied Materials Inc" },
  { symbol: "CSCO", name: "Cisco Systems Inc" },
  { symbol: "NOW", name: "ServiceNow Inc" },
  { symbol: "INTU", name: "Intuit Inc" },
  { symbol: "PANW", name: "Palo Alto Networks Inc" },
  { symbol: "CRWD", name: "CrowdStrike Holdings" },
  { symbol: "ZS", name: "Zscaler Inc" },
  { symbol: "FTNT", name: "Fortinet Inc" },
  { symbol: "WDAY", name: "Workday Inc" },
  { symbol: "TEAM", name: "Atlassian Corp" },
  { symbol: "MDB", name: "MongoDB Inc" },
  { symbol: "HUBS", name: "HubSpot Inc" },
  { symbol: "TWLO", name: "Twilio Inc" },
  { symbol: "OKTA", name: "Okta Inc" },
  { symbol: "DOCU", name: "DocuSign Inc" },
  { symbol: "ZM", name: "Zoom Communications Inc" },
  { symbol: "RBLX", name: "Roblox Corp" },
  { symbol: "EA", name: "Electronic Arts Inc" },
  { symbol: "TTWO", name: "Take-Two Interactive Software" },
  { symbol: "APP", name: "AppLovin Corp" },
  { symbol: "ANET", name: "Arista Networks Inc" },
  { symbol: "JNPR", name: "Juniper Networks Inc" },
  { symbol: "HPQ", name: "HP Inc" },
  { symbol: "DELL", name: "Dell Technologies Inc" },
  { symbol: "WDC", name: "Western Digital Corp" },
  { symbol: "STX", name: "Seagate Technology Holdings" },
  { symbol: "ON", name: "ON Semiconductor Corp" },
  { symbol: "SWKS", name: "Skyworks Solutions Inc" },
  { symbol: "TER", name: "Teradyne Inc" },
  { symbol: "ENPH", name: "Enphase Energy Inc" },
  { symbol: "SEDG", name: "SolarEdge Technologies Inc" },
  { symbol: "ASML", name: "ASML Holding NV" },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing" },
  { symbol: "ARM", name: "Arm Holdings plc" },
  // Healthcare / pharma / biotech / medtech
  { symbol: "UNH", name: "UnitedHealth Group Inc" },
  { symbol: "LLY", name: "Eli Lilly and Co" },
  { symbol: "PFE", name: "Pfizer Inc" },
  { symbol: "MRK", name: "Merck & Co Inc" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "DHR", name: "Danaher Corp" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Co" },
  { symbol: "AMGN", name: "Amgen Inc" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc" },
  { symbol: "SYK", name: "Stryker Corp" },
  { symbol: "BSX", name: "Boston Scientific Corp" },
  { symbol: "ZTS", name: "Zoetis Inc" },
  { symbol: "HCA", name: "HCA Healthcare Inc" },
  { symbol: "ELV", name: "Elevance Health Inc" },
  { symbol: "HUM", name: "Humana Inc" },
  { symbol: "CI", name: "Cigna Group" },
  { symbol: "BIIB", name: "Biogen Inc" },
  { symbol: "ILMN", name: "Illumina Inc" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc" },
  { symbol: "DXCM", name: "DexCom Inc" },
  { symbol: "ALGN", name: "Align Technology Inc" },
  // Financials / insurance
  { symbol: "GS", name: "Goldman Sachs Group Inc" },
  { symbol: "WFC", name: "Wells Fargo & Co" },
  { symbol: "C", name: "Citigroup Inc" },
  { symbol: "AXP", name: "American Express Co" },
  { symbol: "BLK", name: "BlackRock Inc" },
  { symbol: "SPGI", name: "S&P Global Inc" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc" },
  { symbol: "CME", name: "CME Group Inc" },
  { symbol: "MMC", name: "Marsh & McLennan Companies" },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "PGR", name: "Progressive Corp" },
  { symbol: "TRV", name: "Travelers Companies Inc" },
  { symbol: "ALL", name: "Allstate Corp" },
  { symbol: "MET", name: "MetLife Inc" },
  { symbol: "PRU", name: "Prudential Financial Inc" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "PNC", name: "PNC Financial Services Group" },
  { symbol: "TFC", name: "Truist Financial Corp" },
  { symbol: "BK", name: "Bank of New York Mellon Corp" },
  // Industrials / aerospace & defense / transport
  { symbol: "RTX", name: "RTX Corp" },
  { symbol: "NOC", name: "Northrop Grumman Corp" },
  { symbol: "GD", name: "General Dynamics Corp" },
  { symbol: "HON", name: "Honeywell International Inc" },
  { symbol: "CAT", name: "Caterpillar Inc" },
  { symbol: "DE", name: "Deere & Co" },
  { symbol: "ETN", name: "Eaton Corp plc" },
  { symbol: "EMR", name: "Emerson Electric Co" },
  { symbol: "ITW", name: "Illinois Tool Works Inc" },
  { symbol: "PH", name: "Parker Hannifin Corp" },
  { symbol: "ROK", name: "Rockwell Automation Inc" },
  { symbol: "CSX", name: "CSX Corp" },
  { symbol: "NSC", name: "Norfolk Southern Corp" },
  { symbol: "UNP", name: "Union Pacific Corp" },
  { symbol: "WM", name: "Waste Management Inc" },
  { symbol: "RSG", name: "Republic Services Inc" },
  // Consumer discretionary / retail
  { symbol: "HD", name: "Home Depot Inc" },
  { symbol: "LOW", name: "Lowe's Companies Inc" },
  { symbol: "COST", name: "Costco Wholesale Corp" },
  { symbol: "TJX", name: "TJX Companies Inc" },
  { symbol: "ROST", name: "Ross Stores Inc" },
  { symbol: "BKNG", name: "Booking Holdings Inc" },
  { symbol: "MAR", name: "Marriott International Inc" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings" },
  { symbol: "YUM", name: "Yum! Brands Inc" },
  { symbol: "DPZ", name: "Domino's Pizza Inc" },
  { symbol: "EBAY", name: "eBay Inc" },
  { symbol: "ETSY", name: "Etsy Inc" },
  { symbol: "BBY", name: "Best Buy Co Inc" },
  { symbol: "GPS", name: "Gap Inc" },
  { symbol: "ULTA", name: "Ulta Beauty Inc" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc" },
  { symbol: "AZO", name: "AutoZone Inc" },
  // Consumer staples
  { symbol: "CL", name: "Colgate-Palmolive Co" },
  { symbol: "GIS", name: "General Mills Inc" },
  { symbol: "K", name: "Kellanova" },
  { symbol: "HSY", name: "Hershey Co" },
  { symbol: "STZ", name: "Constellation Brands Inc" },
  { symbol: "KHC", name: "Kraft Heinz Co" },
  { symbol: "MDLZ", name: "Mondelez International Inc" },
  { symbol: "KR", name: "Kroger Co" },
  { symbol: "SYY", name: "Sysco Corp" },
  { symbol: "EL", name: "Estee Lauder Companies" },
  // Energy
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger NV" },
  { symbol: "EOG", name: "EOG Resources Inc" },
  { symbol: "MPC", name: "Marathon Petroleum Corp" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "VLO", name: "Valero Energy Corp" },
  { symbol: "OXY", name: "Occidental Petroleum Corp" },
  { symbol: "WMB", name: "Williams Companies Inc" },
  { symbol: "KMI", name: "Kinder Morgan Inc" },
  { symbol: "HAL", name: "Halliburton Co" },
  { symbol: "DVN", name: "Devon Energy Corp" },
  // Materials
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "APD", name: "Air Products and Chemicals" },
  { symbol: "SHW", name: "Sherwin-Williams Co" },
  { symbol: "ECL", name: "Ecolab Inc" },
  { symbol: "NEM", name: "Newmont Corp" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc" },
  { symbol: "DOW", name: "Dow Inc" },
  { symbol: "DD", name: "DuPont de Nemours Inc" },
  { symbol: "NUE", name: "Nucor Corp" },
  { symbol: "STLD", name: "Steel Dynamics Inc" },
  // Utilities
  { symbol: "NEE", name: "NextEra Energy Inc" },
  { symbol: "AEP", name: "American Electric Power Co" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "EXC", name: "Exelon Corp" },
  { symbol: "XEL", name: "Xcel Energy Inc" },
  { symbol: "ED", name: "Consolidated Edison Inc" },
  { symbol: "WEC", name: "WEC Energy Group Inc" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "PEG", name: "Public Service Enterprise Group" },
  { symbol: "FE", name: "FirstEnergy Corp" },
  // REITs
  { symbol: "PLD", name: "Prologis Inc" },
  { symbol: "AMT", name: "American Tower Corp" },
  { symbol: "EQIX", name: "Equinix Inc" },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "SPG", name: "Simon Property Group Inc" },
  { symbol: "DLR", name: "Digital Realty Trust Inc" },
  { symbol: "WELL", name: "Welltower Inc" },
  { symbol: "AVB", name: "AvalonBay Communities Inc" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "VTR", name: "Ventas Inc" },
  // Communication services / media
  { symbol: "TMUS", name: "T-Mobile US Inc" },
  { symbol: "CHTR", name: "Charter Communications Inc" },
  { symbol: "WBD", name: "Warner Bros Discovery Inc" },
  { symbol: "PARA", name: "Paramount Global" },
  { symbol: "MTCH", name: "Match Group Inc" },
  { symbol: "PINS", name: "Pinterest Inc" },
  { symbol: "TTD", name: "Trade Desk Inc" },
  // Automotive
  { symbol: "TM", name: "Toyota Motor Corp" },
  { symbol: "HMC", name: "Honda Motor Co" },
  { symbol: "STLA", name: "Stellantis NV" },
  { symbol: "HOG", name: "Harley-Davidson Inc" },
  // Fintech / crypto-adjacent
  { symbol: "COIN", name: "Coinbase Global Inc" },
  { symbol: "SQ", name: "Block Inc" },
  { symbol: "AFRM", name: "Affirm Holdings Inc" },
  { symbol: "HOOD", name: "Robinhood Markets Inc" },
  { symbol: "MSTR", name: "Strategy Inc" },
  // Travel / leisure
  { symbol: "EXPE", name: "Expedia Group Inc" },
  { symbol: "CCL", name: "Carnival Corp" },
  { symbol: "RCL", name: "Royal Caribbean Group" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
];

export const TRACKED_TICKERS: string[] = TRACKED_SYMBOLS.map((s) => s.symbol);
