// Single source of truth for the equity universe every scanner tracks
// (fetch-stock-data, fundamentals-scanner, earnings-scanner, insider-scanner).
// Previously each function kept its own copy of this list, and they drifted:
// insider-scanner still had the original ~74-symbol list months after the
// other three grew to 115, silently missing insider-activity coverage on
// every ticker added since (including KMB, ABBV, and the rest of the
// dividend/small-cap additions). Import from here instead of hand-copying.
export interface TrackedSymbol { symbol: string; name: string }

export const TRACKED_SYMBOLS: TrackedSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc" },
  { symbol: "NVDA", name: "NVIDIA Corp" },
  { symbol: "TSLA", name: "Tesla Inc" },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "MSFT", name: "Microsoft Corp" },
  { symbol: "GOOGL", name: "Alphabet Inc" },
  { symbol: "AMZN", name: "Amazon.com Inc" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "NFLX", name: "Netflix Inc" },
  { symbol: "DIS", name: "Walt Disney Co" },
  { symbol: "JPM", name: "JPMorgan Chase & Co" },
  { symbol: "BAC", name: "Bank of America Corp" },
  { symbol: "XOM", name: "Exxon Mobil Corp" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "KO", name: "Coca-Cola Co" },
  { symbol: "WMT", name: "Walmart Inc" },
  { symbol: "V", name: "Visa Inc" },
  { symbol: "CRM", name: "Salesforce Inc" },
  { symbol: "ORCL", name: "Oracle Corp" },
  { symbol: "INTC", name: "Intel Corp" },
  { symbol: "ADBE", name: "Adobe Inc" },
  { symbol: "UBER", name: "Uber Technologies" },
  { symbol: "SOFI", name: "SoFi Technologies" },
  { symbol: "NIO", name: "NIO Inc" },
  { symbol: "PLUG", name: "Plug Power Inc" },
  { symbol: "SIRI", name: "Sirius XM Holdings" },
  { symbol: "NOK", name: "Nokia Corp" },
  { symbol: "F", name: "Ford Motor Co" },
  { symbol: "GPRO", name: "GoPro Inc" },
  { symbol: "CLOV", name: "Clover Health Investments" },
  { symbol: "BBAI", name: "BigBear.ai Holdings" },
  { symbol: "MARA", name: "MARA Holdings" },
  { symbol: "RIOT", name: "Riot Platforms" },
  { symbol: "SNDL", name: "SNDL Inc" },
  { symbol: "LCID", name: "Lucid Group" },
  { symbol: "CHPT", name: "ChargePoint Holdings" },
  { symbol: "FCEL", name: "FuelCell Energy" },
  { symbol: "IQ", name: "iQIYI Inc" },
  { symbol: "SNOW", name: "Snowflake Inc" },
  { symbol: "DDOG", name: "Datadog Inc" },
  { symbol: "NET", name: "Cloudflare Inc" },
  { symbol: "SHOP", name: "Shopify Inc" },
  { symbol: "PYPL", name: "PayPal Holdings" },
  { symbol: "ROKU", name: "Roku Inc" },
  { symbol: "SNAP", name: "Snap Inc" },
  { symbol: "ABNB", name: "Airbnb Inc" },
  { symbol: "DASH", name: "DoorDash Inc" },
  { symbol: "TGT", name: "Target Corp" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "NKE", name: "Nike Inc" },
  { symbol: "SBUX", name: "Starbucks Corp" },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "SCHW", name: "Charles Schwab Corp" },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "MRNA", name: "Moderna Inc" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "CVS", name: "CVS Health Corp" },
  { symbol: "BA", name: "Boeing Co" },
  { symbol: "GE", name: "General Electric Co" },
  { symbol: "FDX", name: "FedEx Corp" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "AAL", name: "American Airlines Group" },
  { symbol: "LUV", name: "Southwest Airlines Co" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "QCOM", name: "Qualcomm Inc" },
  { symbol: "RIVN", name: "Rivian Automotive" },
  { symbol: "GM", name: "General Motors Co" },
  { symbol: "T", name: "AT&T Inc" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "CMCSA", name: "Comcast Corp" },
  // Small-cap ($300M-$2B-ish) -- everything above is large/mega-cap, so a
  // market-cap-based small-cap screen had nothing real to actually screen
  // without adding genuine small-cap names across a spread of sectors.
  { symbol: "CENX", name: "Century Aluminum Co" },
  { symbol: "ARRY", name: "Array Technologies" },
  { symbol: "SHLS", name: "Shoals Technologies Group" },
  { symbol: "PUBM", name: "PubMatic Inc" },
  { symbol: "MGNI", name: "Magnite Inc" },
  { symbol: "PERI", name: "Perion Network Ltd" },
  { symbol: "APPS", name: "Digital Turbine Inc" },
  { symbol: "AMRX", name: "Amneal Pharmaceuticals" },
  { symbol: "EVH", name: "Evolent Health Inc" },
  { symbol: "PGNY", name: "Progyny Inc" },
  { symbol: "CORT", name: "Corcept Therapeutics" },
  { symbol: "SUPN", name: "Supernus Pharmaceuticals" },
  { symbol: "BBW", name: "Build-A-Bear Workshop" },
  { symbol: "DLTH", name: "Duluth Trading Co" },
  { symbol: "DBI", name: "Designer Brands Inc" },
  { symbol: "CURV", name: "Torrid Holdings Inc" },
  { symbol: "TALO", name: "Talos Energy Inc" },
  { symbol: "CRK", name: "Comstock Resources Inc" },
  { symbol: "AMBA", name: "Ambarella Inc" },
  { symbol: "MXL", name: "MaxLinear Inc" },
  { symbol: "CEVA", name: "CEVA Inc" },
  { symbol: "PSTL", name: "Postal Realty Trust" },
  { symbol: "GNE", name: "Genie Energy Ltd" },
  { symbol: "RAMP", name: "LiveRamp Holdings" },
  // Steady dividend payers -- deliberately boring, cash-generative
  // businesses (consumer staples, healthcare, utilities, industrials) as a
  // counterweight to the site's growth/momentum-heavy screens elsewhere.
  { symbol: "KMB", name: "Kimberly-Clark Corp" },
  { symbol: "ABBV", name: "AbbVie Inc" },
  { symbol: "PG", name: "Procter & Gamble Co" },
  { symbol: "PEP", name: "PepsiCo Inc" },
  { symbol: "MMM", name: "3M Co" },
  { symbol: "MO", name: "Altria Group Inc" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "O", name: "Realty Income Corp" },
  { symbol: "CVX", name: "Chevron Corp" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "MCD", name: "McDonald's Corp" },
  { symbol: "LMT", name: "Lockheed Martin Corp" },
  { symbol: "DUK", name: "Duke Energy Corp" },
  { symbol: "SO", name: "Southern Co" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MP", name: "MP Materials Corp" },
  // Broad expansion (Aug 2026) -- the list above was a solid but narrow
  // cross-section. fetch-stock-data now processes the universe in
  // stalest-first partial batches instead of "everyone, every 5 minutes",
  // which is what makes a list this size safe to track without blowing
  // past Supabase's edge function execution ceiling -- see the BATCH_LIMIT
  // comment in fetch-stock-data/index.ts. Grouped by sector purely for
  // human readability; every scanner just imports the flat array.
  // Technology / software / semiconductors
  { symbol: "AVGO", name: "Broadcom Inc" },
  { symbol: "TXN", name: "Texas Instruments Inc" },
  { symbol: "ADI", name: "Analog Devices Inc" },
  { symbol: "LRCX", name: "Lam Research Corp" },
  { symbol: "KLAC", name: "KLA Corp" },
  { symbol: "AMAT", name: "Applied Materials Inc" },
  { symbol: "CSCO", name: "Cisco Systems Inc" },
  { symbol: "NOW", name: "ServiceNow Inc" },
  { symbol: "INTU", name: "Intuit Inc" },
  { symbol: "PANW", name: "Palo Alto Networks Inc" },
  { symbol: "CRWD", name: "CrowdStrike Holdings" },
  { symbol: "ZS", name: "Zscaler Inc" },
  { symbol: "FTNT", name: "Fortinet Inc" },
  { symbol: "WDAY", name: "Workday Inc" },
  { symbol: "TEAM", name: "Atlassian Corp" },
  { symbol: "MDB", name: "MongoDB Inc" },
  { symbol: "HUBS", name: "HubSpot Inc" },
  { symbol: "TWLO", name: "Twilio Inc" },
  { symbol: "OKTA", name: "Okta Inc" },
  { symbol: "DOCU", name: "DocuSign Inc" },
  { symbol: "ZM", name: "Zoom Communications Inc" },
  { symbol: "RBLX", name: "Roblox Corp" },
  { symbol: "EA", name: "Electronic Arts Inc" },
  { symbol: "TTWO", name: "Take-Two Interactive Software" },
  { symbol: "APP", name: "AppLovin Corp" },
  { symbol: "ANET", name: "Arista Networks Inc" },
  { symbol: "HPQ", name: "HP Inc" },
  { symbol: "DELL", name: "Dell Technologies Inc" },
  { symbol: "WDC", name: "Western Digital Corp" },
  { symbol: "STX", name: "Seagate Technology Holdings" },
  { symbol: "ON", name: "ON Semiconductor Corp" },
  { symbol: "SWKS", name: "Skyworks Solutions Inc" },
  { symbol: "TER", name: "Teradyne Inc" },
  { symbol: "ENPH", name: "Enphase Energy Inc" },
  { symbol: "SEDG", name: "SolarEdge Technologies Inc" },
  { symbol: "ASML", name: "ASML Holding NV" },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing" },
  { symbol: "ARM", name: "Arm Holdings plc" },
  // Healthcare / pharma / biotech / medtech
  { symbol: "UNH", name: "UnitedHealth Group Inc" },
  { symbol: "LLY", name: "Eli Lilly and Co" },
  { symbol: "PFE", name: "Pfizer Inc" },
  { symbol: "MRK", name: "Merck & Co Inc" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "DHR", name: "Danaher Corp" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Co" },
  { symbol: "AMGN", name: "Amgen Inc" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc" },
  { symbol: "SYK", name: "Stryker Corp" },
  { symbol: "BSX", name: "Boston Scientific Corp" },
  { symbol: "ZTS", name: "Zoetis Inc" },
  { symbol: "HCA", name: "HCA Healthcare Inc" },
  { symbol: "ELV", name: "Elevance Health Inc" },
  { symbol: "HUM", name: "Humana Inc" },
  { symbol: "CI", name: "Cigna Group" },
  { symbol: "BIIB", name: "Biogen Inc" },
  { symbol: "ILMN", name: "Illumina Inc" },
  { symbol: "IDXX", name: "IDEXX Laboratories Inc" },
  { symbol: "DXCM", name: "DexCom Inc" },
  { symbol: "ALGN", name: "Align Technology Inc" },
  // Financials / insurance
  { symbol: "GS", name: "Goldman Sachs Group Inc" },
  { symbol: "WFC", name: "Wells Fargo & Co" },
  { symbol: "C", name: "Citigroup Inc" },
  { symbol: "AXP", name: "American Express Co" },
  { symbol: "BLK", name: "BlackRock Inc" },
  { symbol: "SPGI", name: "S&P Global Inc" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc" },
  { symbol: "CME", name: "CME Group Inc" },
  { symbol: "MRSH", name: "Marsh McLennan" },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "PGR", name: "Progressive Corp" },
  { symbol: "TRV", name: "Travelers Companies Inc" },
  { symbol: "ALL", name: "Allstate Corp" },
  { symbol: "MET", name: "MetLife Inc" },
  { symbol: "PRU", name: "Prudential Financial Inc" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "PNC", name: "PNC Financial Services Group" },
  { symbol: "TFC", name: "Truist Financial Corp" },
  { symbol: "BK", name: "Bank of New York Mellon Corp" },
  // Industrials / aerospace & defense / transport
  { symbol: "RTX", name: "RTX Corp" },
  { symbol: "NOC", name: "Northrop Grumman Corp" },
  { symbol: "GD", name: "General Dynamics Corp" },
  { symbol: "HON", name: "Honeywell International Inc" },
  { symbol: "CAT", name: "Caterpillar Inc" },
  { symbol: "DE", name: "Deere & Co" },
  { symbol: "ETN", name: "Eaton Corp plc" },
  { symbol: "EMR", name: "Emerson Electric Co" },
  { symbol: "ITW", name: "Illinois Tool Works Inc" },
  { symbol: "PH", name: "Parker Hannifin Corp" },
  { symbol: "ROK", name: "Rockwell Automation Inc" },
  { symbol: "CSX", name: "CSX Corp" },
  { symbol: "NSC", name: "Norfolk Southern Corp" },
  { symbol: "UNP", name: "Union Pacific Corp" },
  { symbol: "WM", name: "Waste Management Inc" },
  { symbol: "RSG", name: "Republic Services Inc" },
  // Consumer discretionary / retail
  { symbol: "HD", name: "Home Depot Inc" },
  { symbol: "LOW", name: "Lowe's Companies Inc" },
  { symbol: "COST", name: "Costco Wholesale Corp" },
  { symbol: "TJX", name: "TJX Companies Inc" },
  { symbol: "ROST", name: "Ross Stores Inc" },
  { symbol: "BKNG", name: "Booking Holdings Inc" },
  { symbol: "MAR", name: "Marriott International Inc" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings" },
  { symbol: "YUM", name: "Yum! Brands Inc" },
  { symbol: "DPZ", name: "Domino's Pizza Inc" },
  { symbol: "EBAY", name: "eBay Inc" },
  { symbol: "ETSY", name: "Etsy Inc" },
  { symbol: "BBY", name: "Best Buy Co Inc" },
  { symbol: "GAP", name: "Gap Inc" },
  { symbol: "ULTA", name: "Ulta Beauty Inc" },
  { symbol: "ORLY", name: "O'Reilly Automotive Inc" },
  { symbol: "AZO", name: "AutoZone Inc" },
  // Consumer staples
  { symbol: "CL", name: "Colgate-Palmolive Co" },
  { symbol: "GIS", name: "General Mills Inc" },
  { symbol: "HSY", name: "Hershey Co" },
  { symbol: "STZ", name: "Constellation Brands Inc" },
  { symbol: "KHC", name: "Kraft Heinz Co" },
  { symbol: "MDLZ", name: "Mondelez International Inc" },
  { symbol: "KR", name: "Kroger Co" },
  { symbol: "SYY", name: "Sysco Corp" },
  { symbol: "EL", name: "Estee Lauder Companies" },
  // Energy
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger NV" },
  { symbol: "EOG", name: "EOG Resources Inc" },
  { symbol: "MPC", name: "Marathon Petroleum Corp" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "VLO", name: "Valero Energy Corp" },
  { symbol: "OXY", name: "Occidental Petroleum Corp" },
  { symbol: "WMB", name: "Williams Companies Inc" },
  { symbol: "KMI", name: "Kinder Morgan Inc" },
  { symbol: "HAL", name: "Halliburton Co" },
  { symbol: "DVN", name: "Devon Energy Corp" },
  // Materials
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "APD", name: "Air Products and Chemicals" },
  { symbol: "SHW", name: "Sherwin-Williams Co" },
  { symbol: "ECL", name: "Ecolab Inc" },
  { symbol: "NEM", name: "Newmont Corp" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc" },
  { symbol: "DOW", name: "Dow Inc" },
  { symbol: "DD", name: "DuPont de Nemours Inc" },
  { symbol: "NUE", name: "Nucor Corp" },
  { symbol: "STLD", name: "Steel Dynamics Inc" },
  // Utilities
  { symbol: "NEE", name: "NextEra Energy Inc" },
  { symbol: "AEP", name: "American Electric Power Co" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "EXC", name: "Exelon Corp" },
  { symbol: "XEL", name: "Xcel Energy Inc" },
  { symbol: "ED", name: "Consolidated Edison Inc" },
  { symbol: "WEC", name: "WEC Energy Group Inc" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "PEG", name: "Public Service Enterprise Group" },
  { symbol: "FE", name: "FirstEnergy Corp" },
  // REITs
  { symbol: "PLD", name: "Prologis Inc" },
  { symbol: "AMT", name: "American Tower Corp" },
  { symbol: "EQIX", name: "Equinix Inc" },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "SPG", name: "Simon Property Group Inc" },
  { symbol: "DLR", name: "Digital Realty Trust Inc" },
  { symbol: "WELL", name: "Welltower Inc" },
  { symbol: "AVB", name: "AvalonBay Communities Inc" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "VTR", name: "Ventas Inc" },
  // Communication services / media
  { symbol: "TMUS", name: "T-Mobile US Inc" },
  { symbol: "CHTR", name: "Charter Communications Inc" },
  { symbol: "WBD", name: "Warner Bros Discovery Inc" },
  { symbol: "PARA", name: "Paramount Global" },
  { symbol: "MTCH", name: "Match Group Inc" },
  { symbol: "PINS", name: "Pinterest Inc" },
  { symbol: "TTD", name: "Trade Desk Inc" },
  // Automotive
  { symbol: "TM", name: "Toyota Motor Corp" },
  { symbol: "HMC", name: "Honda Motor Co" },
  { symbol: "STLA", name: "Stellantis NV" },
  { symbol: "HOG", name: "Harley-Davidson Inc" },
  // Fintech / crypto-adjacent
  { symbol: "COIN", name: "Coinbase Global Inc" },
  { symbol: "XYZ", name: "Block Inc" },
  { symbol: "AFRM", name: "Affirm Holdings Inc" },
  { symbol: "HOOD", name: "Robinhood Markets Inc" },
  { symbol: "MSTR", name: "Strategy Inc" },
  // Travel / leisure
  { symbol: "EXPE", name: "Expedia Group Inc" },
  { symbol: "CCL", name: "Carnival Corp" },
  { symbol: "RCL", name: "Royal Caribbean Group" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
  // Round 2 expansion (Aug 2026) -- insider-scanner picked up the same
  // stalest-first partial-batching fetch-stock-data got, so it's now safe
  // to keep growing this list without either of them approaching Supabase's
  // ~150s edge function ceiling. Options-scanner and fundamentals/earnings-
  // scanner were already comfortably clear of it at this size (measured
  // live, not assumed) and scale automatically.
  // Technology / software / semis (round 2)
  { symbol: "NXPI", name: "NXP Semiconductors NV" },
  { symbol: "MRVL", name: "Marvell Technology Inc" },
  { symbol: "MPWR", name: "Monolithic Power Systems" },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "SNPS", name: "Synopsys Inc" },
  { symbol: "ADSK", name: "Autodesk Inc" },
  { symbol: "VEEV", name: "Veeva Systems Inc" },
  { symbol: "DT", name: "Dynatrace Inc" },
  { symbol: "GTLB", name: "GitLab Inc" },
  { symbol: "S", name: "SentinelOne Inc" },
  { symbol: "TENB", name: "Tenable Holdings Inc" },
  { symbol: "QLYS", name: "Qualys Inc" },
  { symbol: "CHKP", name: "Check Point Software Technologies" },
  { symbol: "PATH", name: "UiPath Inc" },
  { symbol: "BILL", name: "Bill.com Holdings Inc" },
  { symbol: "PCTY", name: "Paylocity Holding Corp" },
  { symbol: "PAYC", name: "Paycom Software Inc" },
  { symbol: "NTNX", name: "Nutanix Inc" },
  { symbol: "PSTG", name: "Pure Storage Inc" },
  { symbol: "FIVN", name: "Five9 Inc" },
  { symbol: "ASAN", name: "Asana Inc" },
  { symbol: "MNDY", name: "monday.com Ltd" },
  { symbol: "FROG", name: "JFrog Ltd" },
  { symbol: "ESTC", name: "Elastic NV" },
  { symbol: "DBX", name: "Dropbox Inc" },
  { symbol: "BOX", name: "Box Inc" },
  { symbol: "GDDY", name: "GoDaddy Inc" },
  { symbol: "WIX", name: "Wix.com Ltd" },
  { symbol: "AKAM", name: "Akamai Technologies Inc" },
  { symbol: "FFIV", name: "F5 Inc" },
  { symbol: "NTAP", name: "NetApp Inc" },
  { symbol: "CIEN", name: "Ciena Corp" },
  { symbol: "COHR", name: "Coherent Corp" },
  { symbol: "LITE", name: "Lumentum Holdings Inc" },
  { symbol: "GLW", name: "Corning Inc" },
  { symbol: "TDY", name: "Teledyne Technologies Inc" },
  { symbol: "KEYS", name: "Keysight Technologies Inc" },
  { symbol: "TRMB", name: "Trimble Inc" },
  { symbol: "ZBRA", name: "Zebra Technologies Corp" },
  { symbol: "GEN", name: "Gen Digital Inc" },
  { symbol: "MSI", name: "Motorola Solutions Inc" },
  { symbol: "LOGI", name: "Logitech International SA" },
  // Healthcare / pharma / biotech (round 2)
  { symbol: "MCK", name: "McKesson Corp" },
  { symbol: "CAH", name: "Cardinal Health Inc" },
  { symbol: "COR", name: "Cencora Inc" },
  { symbol: "CNC", name: "Centene Corp" },
  { symbol: "MOH", name: "Molina Healthcare Inc" },
  { symbol: "DVA", name: "DaVita Inc" },
  { symbol: "UHS", name: "Universal Health Services" },
  { symbol: "THC", name: "Tenet Healthcare Corp" },
  { symbol: "CRL", name: "Charles River Laboratories" },
  { symbol: "IQV", name: "IQVIA Holdings Inc" },
  { symbol: "A", name: "Agilent Technologies Inc" },
  { symbol: "WAT", name: "Waters Corp" },
  { symbol: "MTD", name: "Mettler-Toledo International" },
  { symbol: "RMD", name: "ResMed Inc" },
  { symbol: "EW", name: "Edwards Lifesciences Corp" },
  { symbol: "BAX", name: "Baxter International Inc" },
  { symbol: "BDX", name: "Becton Dickinson and Co" },
  { symbol: "COO", name: "Cooper Companies Inc" },
  { symbol: "PODD", name: "Insulet Corp" },
  { symbol: "TFX", name: "Teleflex Inc" },
  { symbol: "STE", name: "Steris plc" },
  { symbol: "XRAY", name: "Dentsply Sirona Inc" },
  { symbol: "VTRS", name: "Viatris Inc" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings" },
  { symbol: "NBIX", name: "Neurocrine Biosciences Inc" },
  { symbol: "INCY", name: "Incyte Corp" },
  { symbol: "NTRA", name: "Natera Inc" },
  { symbol: "TECH", name: "Bio-Techne Corp" },
  { symbol: "RGEN", name: "Repligen Corp" },
  { symbol: "ICLR", name: "ICON plc" },
  { symbol: "MEDP", name: "Medpace Holdings Inc" },
  { symbol: "GEHC", name: "GE HealthCare Technologies" },
  // Financials / insurance (round 2)
  { symbol: "MA", name: "Mastercard Inc" },
  { symbol: "FIS", name: "Fidelity National Information Services" },
  { symbol: "FISV", name: "Fiserv Inc" },
  { symbol: "GPN", name: "Global Payments Inc" },
  { symbol: "CBOE", name: "Cboe Global Markets Inc" },
  { symbol: "NDAQ", name: "Nasdaq Inc" },
  { symbol: "MCO", name: "Moody's Corp" },
  { symbol: "TROW", name: "T. Rowe Price Group" },
  { symbol: "STT", name: "State Street Corp" },
  { symbol: "NTRS", name: "Northern Trust Corp" },
  { symbol: "AMP", name: "Ameriprise Financial Inc" },
  { symbol: "RJF", name: "Raymond James Financial" },
  { symbol: "IVZ", name: "Invesco Ltd" },
  { symbol: "BEN", name: "Franklin Resources Inc" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "HBAN", name: "Huntington Bancshares" },
  { symbol: "RF", name: "Regions Financial Corp" },
  { symbol: "CFG", name: "Citizens Financial Group" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "MTB", name: "M&T Bank Corp" },
  { symbol: "ZION", name: "Zions Bancorporation" },
  { symbol: "WTW", name: "Willis Towers Watson plc" },
  { symbol: "L", name: "Loews Corp" },
  { symbol: "HIG", name: "Hartford Financial Services Group" },
  { symbol: "CINF", name: "Cincinnati Financial Corp" },
  { symbol: "GL", name: "Globe Life Inc" },
  { symbol: "AFL", name: "Aflac Inc" },
  { symbol: "UNM", name: "Unum Group" },
  { symbol: "PFG", name: "Principal Financial Group" },
  { symbol: "VOYA", name: "Voya Financial Inc" },
  // Industrials / aerospace & defense / transport (round 2)
  { symbol: "LHX", name: "L3Harris Technologies Inc" },
  { symbol: "TDG", name: "TransDigm Group Inc" },
  { symbol: "TXT", name: "Textron Inc" },
  { symbol: "HII", name: "Huntington Ingalls Industries" },
  { symbol: "LDOS", name: "Leidos Holdings Inc" },
  { symbol: "CTAS", name: "Cintas Corp" },
  { symbol: "FAST", name: "Fastenal Co" },
  { symbol: "PAYX", name: "Paychex Inc" },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "VRSK", name: "Verisk Analytics Inc" },
  { symbol: "IR", name: "Ingersoll Rand Inc" },
  { symbol: "XYL", name: "Xylem Inc" },
  { symbol: "DOV", name: "Dover Corp" },
  { symbol: "AME", name: "Ametek Inc" },
  { symbol: "PWR", name: "Quanta Services Inc" },
  { symbol: "J", name: "Jacobs Solutions Inc" },
  { symbol: "GNRC", name: "Generac Holdings Inc" },
  { symbol: "CMI", name: "Cummins Inc" },
  { symbol: "PCAR", name: "Paccar Inc" },
  { symbol: "ODFL", name: "Old Dominion Freight Line" },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide" },
  { symbol: "EXPD", name: "Expeditors International" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services" },
  { symbol: "KNX", name: "Knight-Swift Transportation" },
  { symbol: "R", name: "Ryder System Inc" },
  // Consumer discretionary / retail (round 2)
  { symbol: "CHWY", name: "Chewy Inc" },
  { symbol: "W", name: "Wayfair Inc" },
  { symbol: "CVNA", name: "Carvana Co" },
  { symbol: "KMX", name: "CarMax Inc" },
  { symbol: "DKS", name: "Dick's Sporting Goods" },
  { symbol: "FIVE", name: "Five Below Inc" },
  { symbol: "BURL", name: "Burlington Stores Inc" },
  { symbol: "TSCO", name: "Tractor Supply Co" },
  { symbol: "WSM", name: "Williams-Sonoma Inc" },
  { symbol: "RH", name: "RH" },
  { symbol: "DECK", name: "Deckers Brands" },
  { symbol: "CROX", name: "Crocs Inc" },
  { symbol: "PVH", name: "PVH Corp" },
  { symbol: "RL", name: "Ralph Lauren Corp" },
  { symbol: "VFC", name: "VF Corp" },
  { symbol: "LEVI", name: "Levi Strauss & Co" },
  { symbol: "HAS", name: "Hasbro Inc" },
  { symbol: "MAT", name: "Mattel Inc" },
  { symbol: "POOL", name: "Pool Corp" },
  { symbol: "LKQ", name: "LKQ Corp" },
  { symbol: "APTV", name: "Aptiv plc" },
  { symbol: "BWA", name: "BorgWarner Inc" },
  // Consumer staples (round 2)
  { symbol: "CHD", name: "Church & Dwight Co" },
  { symbol: "CLX", name: "Clorox Co" },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc" },
  { symbol: "MNST", name: "Monster Beverage Corp" },
  { symbol: "TAP", name: "Molson Coors Beverage Co" },
  { symbol: "ADM", name: "Archer-Daniels-Midland Co" },
  { symbol: "BG", name: "Bunge Global SA" },
  { symbol: "TSN", name: "Tyson Foods Inc" },
  { symbol: "HRL", name: "Hormel Foods Corp" },
  { symbol: "CAG", name: "Conagra Brands Inc" },
  { symbol: "CPB", name: "Campbell's Co" },
  { symbol: "SJM", name: "J.M. Smucker Co" },
  { symbol: "MKC", name: "McCormick & Co" },
  { symbol: "LW", name: "Lamb Weston Holdings" },
  { symbol: "DG", name: "Dollar General Corp" },
  { symbol: "DLTR", name: "Dollar Tree Inc" },
  // Energy (round 2)
  { symbol: "BKR", name: "Baker Hughes Co" },
  { symbol: "FANG", name: "Diamondback Energy Inc" },
  { symbol: "EQT", name: "EQT Corp" },
  { symbol: "TRGP", name: "Targa Resources Corp" },
  { symbol: "OKE", name: "ONEOK Inc" },
  { symbol: "APA", name: "APA Corp" },
  { symbol: "NOV", name: "NOV Inc" },
  { symbol: "FTI", name: "TechnipFMC plc" },
  // Materials (round 2)
  { symbol: "PPG", name: "PPG Industries Inc" },
  { symbol: "IFF", name: "International Flavors & Fragrances" },
  { symbol: "ALB", name: "Albemarle Corp" },
  { symbol: "CE", name: "Celanese Corp" },
  { symbol: "EMN", name: "Eastman Chemical Co" },
  { symbol: "LYB", name: "LyondellBasell Industries" },
  { symbol: "VMC", name: "Vulcan Materials Co" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "PKG", name: "Packaging Corp of America" },
  { symbol: "IP", name: "International Paper Co" },
  { symbol: "BALL", name: "Ball Corp" },
  { symbol: "AVY", name: "Avery Dennison Corp" },
  { symbol: "CF", name: "CF Industries Holdings" },
  { symbol: "MOS", name: "Mosaic Co" },
  // Utilities (round 2)
  { symbol: "D", name: "Dominion Energy Inc" },
  { symbol: "PCG", name: "PG&E Corp" },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "AEE", name: "Ameren Corp" },
  { symbol: "CMS", name: "CMS Energy Corp" },
  { symbol: "DTE", name: "DTE Energy Co" },
  { symbol: "ETR", name: "Entergy Corp" },
  { symbol: "PPL", name: "PPL Corp" },
  { symbol: "NI", name: "NiSource Inc" },
  { symbol: "ATO", name: "Atmos Energy Corp" },
  { symbol: "CNP", name: "CenterPoint Energy Inc" },
  { symbol: "LNT", name: "Alliant Energy Corp" },
  { symbol: "NRG", name: "NRG Energy Inc" },
  { symbol: "AES", name: "AES Corp" },
  { symbol: "PNW", name: "Pinnacle West Capital Corp" },
  // REITs (round 2)
  { symbol: "CCI", name: "Crown Castle Inc" },
  { symbol: "SBAC", name: "SBA Communications Corp" },
  { symbol: "IRM", name: "Iron Mountain Inc" },
  { symbol: "EXR", name: "Extra Space Storage Inc" },
  { symbol: "MAA", name: "Mid-America Apartment Communities" },
  { symbol: "UDR", name: "UDR Inc" },
  { symbol: "ESS", name: "Essex Property Trust" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities" },
  { symbol: "BXP", name: "BXP Inc" },
  { symbol: "VNO", name: "Vornado Realty Trust" },
  { symbol: "KIM", name: "Kimco Realty Corp" },
  { symbol: "REG", name: "Regency Centers Corp" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "HST", name: "Host Hotels & Resorts" },
  { symbol: "INVH", name: "Invitation Homes Inc" },
  // Communication services / media (round 2)
  { symbol: "LYV", name: "Live Nation Entertainment" },
  { symbol: "NWSA", name: "News Corp" },
  { symbol: "FOXA", name: "Fox Corp" },
  { symbol: "OMC", name: "Omnicom Group Inc" },
  // Automotive (round 2)
  { symbol: "LI", name: "Li Auto Inc" },
  { symbol: "XPEV", name: "XPeng Inc" },
  { symbol: "GT", name: "Goodyear Tire & Rubber Co" },
  { symbol: "THO", name: "Thor Industries Inc" },
  // Fintech / crypto-adjacent (round 2)
  { symbol: "UPST", name: "Upstart Holdings Inc" },
  { symbol: "NU", name: "Nu Holdings Ltd" },
  { symbol: "MELI", name: "MercadoLibre Inc" },
  // Travel / leisure (round 2)
  { symbol: "WYNN", name: "Wynn Resorts Ltd" },
  { symbol: "LVS", name: "Las Vegas Sands Corp" },
  { symbol: "MGM", name: "MGM Resorts International" },
  { symbol: "CZR", name: "Caesars Entertainment Inc" },
  { symbol: "DKNG", name: "DraftKings Inc" },
  { symbol: "PENN", name: "Penn Entertainment Inc" },
  { symbol: "LYFT", name: "Lyft Inc" },
  // Growth / consumer / biotech (round 2)
  { symbol: "CELH", name: "Celsius Holdings Inc" },
  { symbol: "OLLI", name: "Ollie's Bargain Outlet Holdings" },
  { symbol: "FND", name: "Floor & Decor Holdings" },
  { symbol: "ELF", name: "e.l.f. Beauty Inc" },
  { symbol: "ONON", name: "On Holding AG" },
  { symbol: "SFM", name: "Sprouts Farmers Market" },
  { symbol: "WING", name: "Wingstop Inc" },
  { symbol: "CAVA", name: "CAVA Group Inc" },
  { symbol: "SHAK", name: "Shake Shack Inc" },
  { symbol: "TXRH", name: "Texas Roadhouse Inc" },
  { symbol: "DUOL", name: "Duolingo Inc" },
  { symbol: "RDDT", name: "Reddit Inc" },
  { symbol: "SPOT", name: "Spotify Technology SA" },
  { symbol: "IOT", name: "Samsara Inc" },
  { symbol: "CRSP", name: "CRISPR Therapeutics AG" },
  { symbol: "SRPT", name: "Sarepta Therapeutics Inc" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals Inc" },
  { symbol: "BMRN", name: "BioMarin Pharmaceutical Inc" },
  { symbol: "EXEL", name: "Exelixis Inc" },
  { symbol: "UTHR", name: "United Therapeutics Corp" },
  { symbol: "JAZZ", name: "Jazz Pharmaceuticals plc" },
  { symbol: "HALO", name: "Halozyme Therapeutics Inc" },
  // Space / deep tech (round 2)
  { symbol: "RKLB", name: "Rocket Lab USA Inc" },
  { symbol: "IONQ", name: "IonQ Inc" },
  // Added on user request (Sep 2026)
  { symbol: "TTMI", name: "TTM Technologies Inc" },
  { symbol: "BIAF", name: "BioAffinity Technologies Inc" },
];

export const TRACKED_TICKERS: string[] = TRACKED_SYMBOLS.map((s) => s.symbol);
