import { Link } from 'react-router-dom';
import { FileText } from 'lucide-react';
import { LegalDoc, LegalSection as S } from '@/components/legal/LegalDoc';
import { LEGAL } from '@/lib/legalConfig';

const Terms = () => (
  <LegalDoc title="Terms of Use" icon={<FileText className="h-5 w-5 text-primary" />}>
    <S title="1. Agreement">
      <p>These Terms govern your use of {LEGAL.serviceName} (the "Service"), operated by {LEGAL.operator} ("we", "us"). By creating an account or using the Service you agree to these Terms, our <Link to="/privacy" className="underline">Privacy Policy</Link> and our <Link to="/legal" className="underline">Disclaimers</Link>. If you don't agree, don't use the Service.</p>
      <p>You must be at least 18 and able to form a binding contract. The Service is designed for people in the United States. We may update these Terms; if a change is material we will post it here and update the effective date, and continuing to use the Service afterward means you accept it.</p>
    </S>

    <S title="2. What the Service is - and is not">
      <p>{LEGAL.serviceName} is a research and education tool. It displays market data, technical indicator readings (Bullish, Neutral or Bearish), fundamentals screens, options and futures information, and tools for tracking a portfolio you enter yourself.</p>
      <p><strong className="text-foreground">We are not a registered investment adviser, broker-dealer, or financial planner.</strong> We do not hold your money, execute trades, or connect to your brokerage. Nothing on the Service is a personal recommendation, a solicitation, or an offer to buy or sell any security, derivative, commodity, or other financial instrument.</p>
    </S>

    <S title="3. No investment advice">
      <p>All readings, scores, patterns, rankings, alerts, chat answers, portfolio notes and other content are generated by automated rules from public data. They are the same for every user, are not based on your personal circumstances, and do not account for your goals, finances, risk tolerance or taxes. A "Bullish" or "Bearish" reading describes what certain indicators currently show; it is not an instruction to buy or sell and it is not a prediction.</p>
      <p>Investing involves risk, including the loss of everything you put in. Options and futures can lose more than you invest. Past performance, including any track record shown on the Service, does not guarantee future results. You alone are responsible for your decisions. Do your own research and consult a licensed professional before acting.</p>
    </S>

    <S title="4. Data and availability">
      <p>Market data and other information come from third-party sources and may be delayed (often by about 15 minutes), incomplete, or wrong. Some figures are calculated by us from that data, for example options greeks and implied volatility, and some data (such as Open Interest) is not provided at all. We do not guarantee accuracy, completeness, timeliness or availability, and the Service may be interrupted, changed or discontinued at any time.</p>
      <p>A demonstration mode may show a saved snapshot of data rather than live data; it says so when active.</p>
    </S>

    <S title="5. Your account">
      <p>You are responsible for your account credentials and for activity under your account. Give accurate information and tell us promptly if you suspect unauthorized use. We may suspend or end accounts that violate these Terms or put the Service or others at risk.</p>
    </S>

    <S title="6. Information you enter">
      <p>You may enter holdings, prices, quantities, alert thresholds, notes, chat messages and similar information. You keep ownership of it and give us permission to store and process it to operate the Service for you, as described in the Privacy Policy. Do not enter brokerage or bank credentials, account numbers, government ID numbers, or other sensitive information - the Service never needs them.</p>
    </S>

    <S title="7. Acceptable use">
      <p>You agree not to:</p>
      <ul className="ml-4 list-disc space-y-1">
        <li>copy, scrape, resell or redistribute the Service's data, readings or content, including through bots or automated bulk access - much of the data is licensed to us for display to you only;</li>
        <li>present the Service's readings to others as investment advice or as your own advisory service;</li>
        <li>attempt to disrupt, overload, probe, or gain unauthorized access to the Service or its systems, or reverse engineer it;</li>
        <li>use the Service for anything unlawful, or to manipulate markets or deceive others.</li>
      </ul>
    </S>

    <S title="8. Automated assistant">
      <p>The in-app assistant answers questions using fixed rules and the same data shown elsewhere on the Service. It can be wrong or incomplete, it does not know your situation, and it is not advice. It declines to tell you what to buy or sell.</p>
    </S>

    <S title="9. Intellectual property and third-party names">
      <p>The Service's software, design and original content belong to us or our licensors. Company, fund and index names and symbols (including S&amp;P 500 and VIX) are trademarks of their respective owners and are used only to identify them; their use does not imply sponsorship or endorsement. Data providers' own terms apply to their data.</p>
    </S>

    <S title="10. Third-party services">
      <p>If you connect a third-party service, such as a Slack webhook for alerts, that service's terms and privacy practices apply to it. We are not responsible for third-party services or for links to them.</p>
    </S>

    <S title="11. Disclaimer of warranties">
      <p>The Service is provided "as is" and "as available", without warranties of any kind, express or implied, including accuracy, fitness for a particular purpose, merchantability, non-infringement, and uninterrupted or error-free operation, to the extent the law allows.</p>
    </S>

    <S title="12. Limitation of liability">
      <p>To the fullest extent the law allows, {LEGAL.operator} and its owners, employees and suppliers are not liable for indirect, incidental, special, consequential or punitive damages, or for any trading or investment loss, lost profit, or lost data, arising from your use of or inability to use the Service, even if we were told it could happen. Our total liability for any claim relating to the Service is limited to the greater of the amount you paid us in the past twelve months or US$100. Some places do not allow certain limits, so parts of this section may not apply to you.</p>
    </S>

    <S title="13. Indemnity">
      <p>You agree to defend and reimburse us for claims, losses and costs arising from your violation of these Terms or misuse of the Service, to the extent the law allows.</p>
    </S>

    <S title="14. Ending use">
      <p>You can stop using the Service at any time and ask us to delete your account (see the Privacy Policy). We may suspend or end the Service or your access at any time. Sections that by their nature should survive (including 3, 4, 7, 9, 11-13 and 15) will survive.</p>
    </S>

    <S title="15. Governing law and disputes">
      <p>These Terms are governed by the laws of {LEGAL.governingLaw}, without regard to its conflict-of-law rules. Disputes will be brought in the courts located there, unless the law requires otherwise. We'll try to resolve concerns informally first - write to us at the address below.</p>
    </S>

    <S title="16. Contact">
      <p>Questions about these Terms: <a href={`mailto:${LEGAL.contactEmail}`} className="underline">{LEGAL.contactEmail}</a>.</p>
    </S>
  </LegalDoc>
);

export default Terms;
